export const imagesCodes = {
    '01n': 'clear',
    '02n': 'clouds',
    '03n': 'clouds',
    '04n': 'clouds',
    '09n': 'rain',
    '10n': 'rain',
    '11n': 'thunderstorm',
    '13n': 'snow',
    '50n': 'mist',
    '01d': 'clear',
    '02d': 'clouds',
    '03d': 'clouds',
    '04d': 'clouds',
    '09d': 'rain',
    '10d': 'rain',
    '11d': 'thunderstorm',
    '13d': 'snow',
    '50d': 'mist',
    '000': 'invalid',
}